import SplashScreen from './splash';
import Dashboard from './dashboard';
import SignIn from './signin';
import ForgotPassword from './signin/ForgotPassword';
import Profile from './profile';
import Attendance from './attendance';
import UnderConstruction from './UnderConstruction';
import Classroom from './classroom';
import ChangePassword from './signin/ChangePassword';
import Assignments from './assignments';
import AssignmentScreen from './assignments/AssignmentScreen';
import AssignmentDetail from './assignments/AssignmentDetail';
import Timetable from './timetable';
import TimeTableScreen from './timetable/TimeTableScreen';
import Result from './result';
import Notices from './notice';
import NoticeBoard from './notice/NoticeBoard';
import Holidays from './holidays';
export {SplashScreen,Dashboard,SignIn,ForgotPassword,Profile,Attendance,UnderConstruction,Classroom,ChangePassword,Assignments,AssignmentScreen,AssignmentDetail,Timetable,TimeTableScreen,Result,Notices,NoticeBoard,Holidays}